kind: Service                             
apiVersion: v1
metadata:
  name: devops.project
  labels:
    app: devops.project
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: devops.project                    
  type: LoadBalancer             
